import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import Navigation from "@/components/Navigation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="max-w-8xl mx-auto">
          <Navigation />
        </header>
        <main className="flex flex-col items-center [&_>_*]:max-w-7xl [&_>_*]:w-full">
          {children}
        </main>
        <footer className="max-w-8xl mx-auto">Footer section</footer>
      </body>
    </html>
  );
}
