export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <section className="bg-slate-200 !max-w-8xl">First section</section>
      <section className="bg-slate-500">Second section</section>
      <section className="bg-slate-700">Third section</section>
    </>
  );
}
