// Sections
import Hero from "@/sections/home/Hero";
import Lessons from "@/sections/home/Lessons";
import Offer from "@/sections/home/Offer";
import Contact from "@/sections/home/Contact";
// Meta
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <section className="!max-w-fullScreen h-[85vh] lg:h-[75vh]">
        <Hero />
      </section>
      <section className="py-12 px-4 sm:px-6 lg:px-8">
        <Offer />
      </section>
      <section className="!max-w-fullScreen">
        <div className="lg:max-w-section m-[0_auto]">
          <Lessons />
        </div>
      </section>
      <section><Contact /></section>
    </>
  );
}
