export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <section className="bg-slate-200 h-[60vh]">First section</section>
      <section className="bg-slate-500 !max-w-8xl h-[60vh]">Second section</section>
      <section className="bg-slate-700 h-[60vh]">Third section</section>
      <section className="bg-slate-700 h-[60vh]">Forth section</section>
      <section className="bg-slate-700 h-[60vh]">Fifth section</section>
    </>
  );
}
